<?php
/**
 * Default Lexicon Entries for CronManager
 *
 * @package cronmanager
 * @subpackage lexicon
 */
$_lang['cronmanager'] = '';
$_lang['cronmanager.active'] = '';
$_lang['cronmanager.create'] = '';
$_lang['cronmanager.cronjoblog'] = '';
$_lang['cronmanager.cronjoblog_desc'] = '';
$_lang['cronmanager.cronjobs'] = '';
$_lang['cronmanager.cronjobs_desc'] = '';
$_lang['cronmanager.debug_mode'] = '';
$_lang['cronmanager.job_started'] = '';
$_lang['cronmanager.job_started_message'] = '';
$_lang['cronmanager.jobs_started'] = '';
$_lang['cronmanager.jobs_started_message'] = '';
$_lang['cronmanager.lastrun'] = '';
$_lang['cronmanager.log.date'] = '';
$_lang['cronmanager.log.message'] = '';
$_lang['cronmanager.log.norecords'] = '';
$_lang['cronmanager.log_day'] = '';
$_lang['cronmanager.log_error'] = '';
$_lang['cronmanager.log_message'] = '';
$_lang['cronmanager.log_messages'] = '';
$_lang['cronmanager.log_view_full'] = '';
$_lang['cronmanager.logs_actions'] = '';
$_lang['cronmanager.logs_delete_selected'] = '';
$_lang['cronmanager.logs_delete_selected_confirm'] = '';
$_lang['cronmanager.logs_delete_selected_confirm_one'] = '';
$_lang['cronmanager.logs_delete_selected_one'] = '';
$_lang['cronmanager.logs_filter_all'] = '';
$_lang['cronmanager.logs_filter_error'] = '';
$_lang['cronmanager.logs_filter_no_error'] = '';
$_lang['cronmanager.logs_purge_confirm'] = '';
$_lang['cronmanager.logs_purge_db_err'] = '';
$_lang['cronmanager.logs_purge_no_err'] = '';
$_lang['cronmanager.logs_purge_nothing'] = '';
$_lang['cronmanager.logs_purge_success'] = '';
$_lang['cronmanager.logs_purge_title'] = '';
$_lang['cronmanager.menu'] = '';
$_lang['cronmanager.menu_desc'] = '';
$_lang['cronmanager.minutes'] = '';
$_lang['cronmanager.minutes_desc'] = '';
$_lang['cronmanager.nextrun'] = '';
$_lang['cronmanager.norecords'] = '';
$_lang['cronmanager.properties'] = '';
$_lang['cronmanager.properties_desc'] = '';
$_lang['cronmanager.remove'] = '';
$_lang['cronmanager.remove_confirm'] = '';
$_lang['cronmanager.run_job'] = '';
$_lang['cronmanager.run_job_confirm'] = '';
$_lang['cronmanager.run_jobs'] = '';
$_lang['cronmanager.run_jobs_confirm'] = '';
$_lang['cronmanager.runempty'] = '';
$_lang['cronmanager.running'] = '';
$_lang['cronmanager.selectasnippet'] = '';
$_lang['cronmanager.settings'] = '';
$_lang['cronmanager.settings_desc'] = '';
$_lang['cronmanager.snippet'] = '';
$_lang['cronmanager.systemsetting_key_err_nv'] = '';
$_lang['cronmanager.systemsetting_usergroup_err_nv'] = '';
$_lang['cronmanager.update'] = '';
$_lang['cronmanager.viewlog'] = '';
$_lang['cronmanager.viewlog_title'] = '';
